"""Made partition id backwards compatible with n-lbaas

Revision ID: 4107009b9be9
Revises: 873ee83aef63
Create Date: 2021-06-24 01:46:21.994074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4107009b9be9'
down_revision = '873ee83aef63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vrid', sa.Column('project_id', sa.String(length=36), nullable=False))
    op.drop_column('vrid', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vrid', sa.Column('owner', mysql.VARCHAR(length=36), nullable=False))
    op.drop_column('vrid', 'project_id')
    # ### end Alembic commands ###
